"""Compatibility snapshots for the documented root-package API."""

from __future__ import annotations

import inspect
import json
from pathlib import Path

import doppel_memory as doppel

ROOT = Path(__file__).resolve().parents[1]

MODEL_FIELDS = {
    "BatchCheckpoint": (
        "cursor",
        "task_name",
        "task_version",
        "schema_version",
        "metadata",
    ),
    "BatchProposalPlan": ("proposals", "next_checkpoint"),
    "BatchReadLimits": ("max_pages", "max_messages", "max_page_size"),
    "BatchRunResult": (
        "proposals",
        "write_results",
        "errors",
        "task",
        "task_version",
        "run_id",
        "scope",
        "window",
        "checkpoint_schema_version",
        "history_pages_read",
        "history_messages_read",
        "committable_checkpoint",
    ),
    "ChatMessage": (
        "actor",
        "text",
        "at",
        "event_id",
        "message_id",
        "sender_id",
        "message_type",
        "reply_to_id",
        "quoted_message_id",
        "thread_id",
        "thread_root_id",
        "attachments",
        "raw",
        "parts",
    ),
    "ConsolidationAction": (
        "decision_id",
        "operation",
        "explanation",
        "confidence",
        "sources",
        "proposal",
        "transition_sources",
    ),
    "ConsolidationActionResult": (
        "decision_id",
        "operation",
        "canonical_write",
        "transitions",
        "complete",
    ),
    "ConsolidationAnalysis": ("decisions",),
    "ConsolidationCheckpoint": (
        "schema_version",
        "cycle",
        "consolidator",
        "consolidator_version",
        "config_fingerprint",
        "input_fingerprint",
        "completed_at",
    ),
    "ConsolidationConfig": (
        "page_size",
        "max_records",
        "max_decisions",
        "minimum_confidence",
    ),
    "ConsolidationDecision": (
        "operation",
        "source_memory_ids",
        "canonical_source_memory_id",
        "confidence",
        "explanation",
    ),
    "ConsolidationInput": ("scope", "records"),
    "ConsolidationPlan": (
        "schema_version",
        "plan_id",
        "run_id",
        "scope",
        "consolidator",
        "consolidator_version",
        "config_fingerprint",
        "input_fingerprint",
        "input_record_count",
        "actions",
        "next_checkpoint",
    ),
    "ConsolidationRunResult": (
        "plan",
        "actions",
        "errors",
        "committable_checkpoint",
    ),
    "ConsolidationSourceSnapshot": (
        "memory_id",
        "state",
        "version",
        "fingerprint",
    ),
    "ConsolidationTransitionResult": (
        "memory_id",
        "status",
        "from_state",
        "to_state",
        "record",
        "error",
    ),
    "ContentPart": ("type", "text", "media", "metadata"),
    "ContentResolution": ("message", "derived_parts", "errors"),
    "ContentResolutionError": ("resolver", "error_type", "message"),
    "DeterministicConsolidatorConfig": (
        "mutable_memory_types",
        "enable_latest_correction",
        "emit_conflicts",
    ),
    "IMImportBatch": (
        "format_version",
        "source",
        "source_version",
        "batch_id",
        "exported_at",
        "cursor",
        "items",
        "metadata",
    ),
    "IMImportItem": ("scope", "message", "source_id", "metadata"),
    "IndexEntry": ("memory_id", "scope_key", "fingerprint", "source_version"),
    "IndexEntryPage": ("entries", "next_cursor", "has_more"),
    "IndexMaintenanceCheckpoint": (
        "schema_version",
        "index_identity",
        "scope_key",
        "phase",
        "cursor",
        "cycle",
    ),
    "IndexMaintenanceFailure": ("memory_id", "stage", "error_type", "message"),
    "IndexMaintenanceReport": (
        "schema_version",
        "index_identity",
        "scope_key",
        "phase",
        "scanned",
        "indexed",
        "skipped",
        "deleted",
        "missing",
        "failed",
        "complete",
        "committable_checkpoint",
        "failures",
    ),
    "IndexOperationResult": (
        "index_identity",
        "status",
        "memory_id",
        "scope_key",
        "fingerprint",
        "source_version",
    ),
    "DeterministicGovernancePolicyConfig": (
        "reinforcement_evidence_threshold",
        "reinforcement_step",
        "reinforcement_cap",
        "expirable_memory_types",
        "enable_decay",
        "ephemeral_retention_classes",
        "decay_after_days",
        "decay_step",
        "decay_floor",
    ),
    "MemoryGovernanceAction": (
        "decision_id",
        "operation",
        "reason",
        "confidence",
        "source",
        "proposal",
        "transition_source",
    ),
    "MemoryGovernanceActionResult": (
        "decision_id",
        "operation",
        "replacement_write",
        "transition",
        "complete",
    ),
    "MemoryGovernanceAnalysis": ("decisions",),
    "MemoryGovernanceCheckpoint": (
        "schema_version",
        "cycle",
        "policy",
        "policy_version",
        "config_fingerprint",
        "input_fingerprint",
        "completed_at",
    ),
    "MemoryGovernanceConfig": (
        "page_size",
        "max_records",
        "max_decisions",
        "minimum_confidence",
    ),
    "MemoryGovernanceDecision": (
        "operation",
        "source_memory_id",
        "target_importance",
        "confidence",
        "reason",
    ),
    "MemoryGovernanceInput": ("scope", "records", "now"),
    "MemoryGovernancePlan": (
        "schema_version",
        "plan_id",
        "run_id",
        "scope",
        "policy",
        "policy_version",
        "evaluated_at",
        "config_fingerprint",
        "input_fingerprint",
        "input_record_count",
        "actions",
        "next_checkpoint",
    ),
    "MemoryGovernanceRunResult": (
        "plan",
        "actions",
        "errors",
        "committable_checkpoint",
    ),
    "MemoryGovernanceSourceSnapshot": (
        "memory_id",
        "state",
        "version",
        "fingerprint",
    ),
    "MemoryGovernanceTransitionResult": (
        "memory_id",
        "status",
        "from_state",
        "to_state",
        "record",
        "error",
    ),
    "MemoryFilter": (
        "kinds",
        "actors",
        "authorities",
        "exclude_authorities",
        "exclude_actors",
        "states",
        "include_inactive",
        "tags",
        "importance_min",
        "time_from",
        "time_to",
    ),
    "MediaRef": (
        "media_id",
        "uri",
        "mime_type",
        "filename",
        "size_bytes",
        "sha256",
        "width",
        "height",
        "duration_ms",
        "metadata",
    ),
    "MemoryProposal": (
        "scope",
        "content",
        "kind",
        "actor",
        "authority",
        "confidence",
        "proposed_state",
        "tags",
        "importance",
        "idempotency_key",
        "source_event_id",
        "source_message_id",
        "processor",
        "processor_version",
        "derived_chain",
        "created_at",
        "metadata",
    ),
    "OpenAICompatibleStructuredOutputConfig": (
        "model",
        "base_url",
        "schema_mode",
        "strict_schema",
        "timeout_seconds",
        "max_request_bytes",
        "max_response_bytes",
        "max_completion_tokens",
        "max_tokens_parameter",
        "temperature",
        "thinking",
    ),
    "PersonalMemoryAnalysis": ("memories",),
    "PersonalMemoryAnalysisRequest": ("scope", "messages"),
    "PersonalMemoryDraft": (
        "content",
        "memory_type",
        "topic_key",
        "event_key",
        "revision_kind",
        "kind",
        "subject",
        "subject_id",
        "confidence",
        "importance",
        "temporal_status",
        "valid_from",
        "valid_to",
        "evidence_ids",
        "tags",
        "metadata",
    ),
    "PersonalMemoryCountResult": (
        "status",
        "value",
        "observed_records",
        "distinct_event_keys",
        "reason",
    ),
    "PersonalMemoryConflictHit": (
        "record",
        "source_memory_ids",
        "matched_source_memory_ids",
        "topic_key",
        "reason",
    ),
    "PersonalMemoryQueryConfig": (
        "page_size",
        "max_records_per_scope",
        "limit",
        "minimum_planner_confidence",
        "minimum_lexical_score",
        "minimum_semantic_score",
        "semantic_candidate_limit",
        "relation_candidate_limit",
        "lexical_weight",
        "semantic_weight",
        "relation_weight",
        "minimum_relation_score",
        "relation_hints_require_match",
        "semantic_fallback_to_lexical",
        "relation_fallback_to_nonrelation",
    ),
    "PersonalMemoryQueryDraft": (
        "intent",
        "search_text",
        "memory_types",
        "topic_keys",
        "temporal_statuses",
        "entity_mentions",
        "relation_hints",
        "subject",
        "subject_id",
        "as_of",
        "time_from",
        "time_to",
        "confidence",
        "explanation",
    ),
    "PersonalMemoryQueryHit": (
        "record",
        "score",
        "lexical_score",
        "semantic_score",
        "relation_score",
        "effective_at",
        "reasons",
    ),
    "PersonalMemoryQueryPlan": (
        "schema_version",
        "plan_id",
        "query",
        "now",
        "scopes",
        "intent",
        "search_text",
        "memory_types",
        "topic_keys",
        "temporal_statuses",
        "entity_mentions",
        "relation_hints",
        "subject",
        "subject_id",
        "as_of",
        "time_from",
        "time_to",
        "planner",
        "planner_version",
        "planner_confidence",
        "explanation",
        "config_fingerprint",
    ),
    "PersonalMemoryQueryRequest": (
        "query",
        "now",
        "default_subject",
        "default_subject_id",
    ),
    "PersonalMemoryQueryResult": (
        "plan",
        "hits",
        "conflicts",
        "matched_record_count",
        "scanned_record_count",
        "scanned_conflict_count",
        "count",
        "ambiguous",
        "warnings",
        "complete",
    ),
    "RelationCandidate": (
        "scope",
        "memory_id",
        "source",
        "score",
        "relation_type",
        "source_entity_id",
        "source_entity_name",
        "target_entity_id",
        "target_entity_name",
        "edge_id",
        "episode_ids",
        "valid_at",
        "invalid_at",
    ),
    "RelationQuery": (
        "query_text",
        "entity_mentions",
        "relation_hints",
        "subject",
        "subject_id",
        "valid_at",
        "time_from",
        "time_to",
    ),
    "PersonalMemoryExtractorConfig": (
        "owner_target_scope",
        "minimum_confidence",
        "max_memories",
        "allowed_source_actors",
        "require_subject_matches_source_actor",
        "proposed_state",
    ),
    "PersonalMemoryMinerConfig": (
        "owner_target_scope",
        "minimum_confidence",
        "max_memories",
        "allowed_source_actors",
        "require_subject_matches_source_actor",
        "proposed_state",
        "page_size",
        "max_messages",
    ),
    "MemoryRecord": (
        "memory_id",
        "kind",
        "scope",
        "content",
        "actor",
        "authority",
        "state",
        "tags",
        "importance",
        "idempotency_key",
        "source_event_id",
        "source_message_id",
        "extractor",
        "created_at",
        "updated_at",
        "version",
        "metadata",
    ),
    "MemoryScope": (
        "user_id",
        "agent_id",
        "platform",
        "chat_type",
        "chat_id",
        "extra_dimensions",
    ),
    "RecallResult": (
        "fact",
        "kind",
        "scope",
        "memory_id",
        "actor",
        "authority",
        "source_event_id",
        "source_message_id",
        "source_episode",
        "extractor",
        "extracted_at",
        "raw_text",
        "derived_chain",
        "valid_at",
        "similarity",
        "state",
    ),
    "StoreCapabilities": (
        "semantic_search",
        "substring_search",
        "full_text_search",
        "temporal_search",
        "graph_relations",
        "metadata_filter",
        "hard_delete",
        "transactions",
        "reranking",
        "pagination",
    ),
    "StoreConformanceCheck": (
        "name",
        "status",
        "capability",
        "issues",
    ),
    "StoreConformanceConfig": (
        "run_id",
        "checks",
        "required_capabilities",
    ),
    "StoreConformanceReport": (
        "schema_version",
        "run_id",
        "store",
        "capabilities",
        "checks",
        "passed_count",
        "skipped_count",
        "failed_count",
    ),
    "StructuredGenerationRequest": (
        "instructions",
        "input",
        "output_schema",
    ),
    "VectorBackfillResult": ("report", "next_cursor", "has_more"),
    "VectorIndexConfig": (
        "create_extension",
        "create_hnsw_index",
        "embedding_batch_size",
        "hnsw_m",
        "hnsw_ef_construction",
    ),
    "VectorIndexFailure": ("memory_id", "stage", "error_type", "message"),
    "VectorIndexReport": (
        "schema_version",
        "profile",
        "attempted",
        "indexed",
        "skipped",
        "failed",
        "failures",
    ),
    "StyleMinerConfig": (
        "min_messages",
        "page_size",
        "accepted_message_types",
        "target_scope",
        "short_message_chars",
        "phrase_ngram_min",
        "phrase_ngram_max",
        "min_phrase_messages",
        "min_phrase_ratio",
        "max_common_phrases",
        "max_source_ids",
    ),
    "StyleDirective": (
        "feature",
        "instruction",
        "evidence",
        "confidence",
        "priority",
    ),
    "StyleGuidance": (
        "schema_version",
        "professor",
        "professor_version",
        "profile_fingerprint",
        "config_fingerprint",
        "source_analyzer",
        "source_analyzer_version",
        "source_message_count",
        "usable",
        "directives",
        "prompt",
        "omitted_features",
        "warnings",
    ),
    "StyleProfessorConfig": (
        "min_reliable_messages",
        "full_confidence_messages",
        "max_prompt_chars",
        "include_common_phrases",
        "max_common_phrases",
        "max_phrase_chars",
    ),
    "StyleProfile": (
        "schema_version",
        "analyzer",
        "analyzer_version",
        "message_count",
        "character_count",
        "average_message_length",
        "median_message_length",
        "short_message_threshold",
        "short_message_ratio",
        "question_ratio",
        "exclamation_ratio",
        "emoji_ratio",
        "multiline_ratio",
        "terminal_punctuation_ratio",
        "common_phrases",
        "summary",
    ),
    "StyleQualityConfig": (
        "min_candidate_messages",
        "passing_score",
    ),
    "StyleQualityReport": (
        "schema_version",
        "evaluator",
        "evaluator_version",
        "reference_profile_fingerprint",
        "config_fingerprint",
        "candidate_input_count",
        "candidate_message_count",
        "sufficient_samples",
        "feature_scores",
        "observed",
        "aggregate_score",
        "passed",
        "warnings",
    ),
    "WriteResult": ("status", "record", "error_code", "message"),
}

SIGNATURES = {
    "BatchProposalPolicy.evaluate": (
        ("proposal", "POSITIONAL_OR_KEYWORD"),
        ("context", "POSITIONAL_OR_KEYWORD"),
    ),
    "ContentResolver.resolve": (("message", "POSITIONAL_OR_KEYWORD"),),
    "EmbeddingProvider.embed": (("texts", "POSITIONAL_OR_KEYWORD"),),
    "DoppelClient.__init__": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("backend", "KEYWORD_ONLY"),
        ("retrieval_strategy", "KEYWORD_ONLY"),
        ("reranker", "KEYWORD_ONLY"),
        ("candidate_multiplier", "KEYWORD_ONLY"),
        ("backend_kwargs", "VAR_KEYWORD"),
    ),
    "DoppelClient.consolidate": (
        ("consolidator", "POSITIONAL_OR_KEYWORD"),
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("config", "KEYWORD_ONLY"),
        ("evaluator", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "DoppelClient.govern_personal_memory": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("policy", "KEYWORD_ONLY"),
        ("now", "KEYWORD_ONLY"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("config", "KEYWORD_ONLY"),
        ("evaluator", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "DoppelClient.process": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("message", "POSITIONAL_OR_KEYWORD"),
        ("processors", "KEYWORD_ONLY"),
        ("policy", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("allowed_scopes", "KEYWORD_ONLY"),
    ),
    "DoppelClient.query_personal_memory": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("planner", "KEYWORD_ONLY"),
        ("now", "KEYWORD_ONLY"),
        ("config", "KEYWORD_ONLY"),
        ("semantic_index", "KEYWORD_ONLY"),
        ("default_subject", "KEYWORD_ONLY"),
        ("default_subject_id", "KEYWORD_ONLY"),
        ("allowed_subject_ids", "KEYWORD_ONLY"),
    ),
    "DoppelClient.materials": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "KEYWORD_ONLY"),
        ("memory_limit", "KEYWORD_ONLY"),
        ("style_sample_limit", "KEYWORD_ONLY"),
        ("policy", "KEYWORD_ONLY"),
        ("style_professor", "KEYWORD_ONLY"),
    ),
    "DoppelClient.run_batch_task": (
        ("task", "POSITIONAL_OR_KEYWORD"),
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("window", "POSITIONAL_OR_KEYWORD"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("history", "KEYWORD_ONLY"),
        ("memories", "KEYWORD_ONLY"),
        ("read_scopes", "KEYWORD_ONLY"),
        ("allowed_scopes", "KEYWORD_ONLY"),
        ("policy", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("read_limits", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "DoppelClient.restore_personal_memory": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("archived_memory_id", "POSITIONAL_OR_KEYWORD"),
        ("target_state", "KEYWORD_ONLY"),
        ("now", "KEYWORD_ONLY"),
        ("config", "KEYWORD_ONLY"),
        ("evaluator", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "DeterministicStyleAnalyzer.analyze": (
        ("messages", "POSITIONAL_OR_KEYWORD"),
        ("config", "KEYWORD_ONLY"),
    ),
    "DeterministicMemoryConsolidator.__init__": (("config", "POSITIONAL_OR_KEYWORD"),),
    "DeterministicMemoryConsolidator.consolidate": (
        ("input", "POSITIONAL_OR_KEYWORD"),
    ),
    "DeterministicPersonalMemoryQueryPlanner.plan": (
        ("request", "POSITIONAL_OR_KEYWORD"),
    ),
    "MemoryBatchTask.propose": (("context", "POSITIONAL_OR_KEYWORD"),),
    "MemoryConsolidator.consolidate": (("input", "POSITIONAL_OR_KEYWORD"),),
    "MemoryGovernancePolicy.evaluate": (("input", "POSITIONAL_OR_KEYWORD"),),
    "MemoryProcessor.process": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("message", "POSITIONAL_OR_KEYWORD"),
    ),
    "PersonalMemoryAnalyzer.analyze": (("request", "POSITIONAL_OR_KEYWORD"),),
    "OpenAICompatibleStructuredOutputModel.__init__": (
        ("config", "POSITIONAL_OR_KEYWORD"),
        ("api_key", "KEYWORD_ONLY"),
        ("headers", "KEYWORD_ONLY"),
        ("client", "KEYWORD_ONLY"),
        ("usage_observer", "KEYWORD_ONLY"),
    ),
    "OpenAICompatibleStructuredOutputModel.generate": (
        ("request", "POSITIONAL_OR_KEYWORD"),
    ),
    "OpenAICompatibleStructuredOutputModel.aclose": (),
    "PersonalMemoryExtractor.__init__": (
        ("analyzer", "POSITIONAL_OR_KEYWORD"),
        ("config", "POSITIONAL_OR_KEYWORD"),
    ),
    "PersonalMemoryExtractor.process": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("message", "POSITIONAL_OR_KEYWORD"),
    ),
    "PersonalMemoryMiner.__init__": (
        ("analyzer", "POSITIONAL_OR_KEYWORD"),
        ("config", "POSITIONAL_OR_KEYWORD"),
    ),
    "PersonalMemoryMiner.propose": (("context", "POSITIONAL_OR_KEYWORD"),),
    "PersonalMemoryQueryPlanner.plan": (("request", "POSITIONAL_OR_KEYWORD"),),
    "ReferencePersonalMemoryAnalyzer.__init__": (("model", "POSITIONAL_OR_KEYWORD"),),
    "ReferencePersonalMemoryAnalyzer.analyze": (("request", "POSITIONAL_OR_KEYWORD"),),
    "ReferencePersonalMemoryQueryPlanner.__init__": (
        ("model", "POSITIONAL_OR_KEYWORD"),
    ),
    "ReferencePersonalMemoryQueryPlanner.plan": (("request", "POSITIONAL_OR_KEYWORD"),),
    "ReferenceMemoryConsolidator.__init__": (("model", "POSITIONAL_OR_KEYWORD"),),
    "ReferenceMemoryConsolidator.consolidate": (("input", "POSITIONAL_OR_KEYWORD"),),
    "MemoryStore.put": (
        ("record", "POSITIONAL_OR_KEYWORD"),
        ("idempotency_key", "KEYWORD_ONLY"),
    ),
    "MemoryStore.scan": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("cursor", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "MemoryStore.search": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "HybridRetrievalStrategy.__init__": (
        ("semantic_index", "POSITIONAL_OR_KEYWORD"),
        ("lexical_strategy", "KEYWORD_ONLY"),
        ("lexical_weight", "KEYWORD_ONLY"),
        ("semantic_weight", "KEYWORD_ONLY"),
        ("rrf_k", "KEYWORD_ONLY"),
        ("candidate_multiplier", "KEYWORD_ONLY"),
        ("fallback_to_lexical", "KEYWORD_ONLY"),
    ),
    "CompositeSemanticIndex.__init__": (
        ("indexes", "POSITIONAL_OR_KEYWORD"),
        ("weights", "KEYWORD_ONLY"),
        ("rrf_k", "KEYWORD_ONLY"),
        ("candidate_multiplier", "KEYWORD_ONLY"),
    ),
    "CompositeSemanticIndex.search": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "CompositeSemanticIndex.search_at": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("valid_at", "KEYWORD_ONLY"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "HybridRetrievalStrategy.search": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "IndexMaintainer.__init__": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("writer", "POSITIONAL_OR_KEYWORD"),
    ),
    "IndexMaintainer.reconcile": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("page_size", "KEYWORD_ONLY"),
    ),
    "IndexWriter.inspect": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("memory_id", "POSITIONAL_OR_KEYWORD"),
    ),
    "IndexWriter.upsert": (("record", "POSITIONAL_OR_KEYWORD"),),
    "IndexWriter.delete": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("memory_id", "POSITIONAL_OR_KEYWORD"),
    ),
    "IndexWriter.scan_entries": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("cursor", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "PostgreSQLStore.__init__": (
        ("dsn", "POSITIONAL_OR_KEYWORD"),
        ("schema", "KEYWORD_ONLY"),
        ("create_schema", "KEYWORD_ONLY"),
        ("min_pool_size", "KEYWORD_ONLY"),
        ("max_pool_size", "KEYWORD_ONLY"),
        ("command_timeout", "KEYWORD_ONLY"),
    ),
    "PostgreSQLVectorIndex.__init__": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("provider", "POSITIONAL_OR_KEYWORD"),
        ("config", "POSITIONAL_OR_KEYWORD"),
    ),
    "PostgreSQLVectorIndex.index_records": (("records", "POSITIONAL_OR_KEYWORD"),),
    "PostgreSQLVectorIndex.backfill": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("cursor", "KEYWORD_ONLY"),
        ("page_size", "KEYWORD_ONLY"),
    ),
    "PostgreSQLVectorIndex.search": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "PersonaMaterialsBuilder.__init__": (
        ("retriever", "POSITIONAL_OR_KEYWORD"),
        ("store", "KEYWORD_ONLY"),
    ),
    "PersonaMaterialsBuilder.build": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "KEYWORD_ONLY"),
        ("memory_limit", "KEYWORD_ONLY"),
        ("style_sample_limit", "KEYWORD_ONLY"),
        ("policy", "KEYWORD_ONLY"),
        ("style_professor", "KEYWORD_ONLY"),
    ),
    "ProposalPolicy.evaluate": (
        ("proposal", "POSITIONAL_OR_KEYWORD"),
        ("message", "POSITIONAL_OR_KEYWORD"),
    ),
    "Reranker.rerank": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("candidates", "POSITIONAL_OR_KEYWORD"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "RetrievalStrategy.search": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "ScopedHistoryReader.read": (
        ("cursor", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
        ("actors", "KEYWORD_ONLY"),
        ("time_from", "KEYWORD_ONLY"),
        ("time_to", "KEYWORD_ONLY"),
    ),
    "ScopedMemoryReader.get": (
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("memory_id", "POSITIONAL_OR_KEYWORD"),
    ),
    "ScopedMemoryReader.recall": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "SemanticIndex.search": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "RelationIndex.search_relations": (
        ("request", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "TemporalSemanticIndex.search_at": (
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("valid_at", "KEYWORD_ONLY"),
        ("filters", "KEYWORD_ONLY"),
        ("limit", "KEYWORD_ONLY"),
    ),
    "StyleAnalyzer.analyze": (
        ("messages", "POSITIONAL_OR_KEYWORD"),
        ("config", "KEYWORD_ONLY"),
    ),
    "StyleMiner.__init__": (
        ("config", "POSITIONAL_OR_KEYWORD"),
        ("analyzer", "KEYWORD_ONLY"),
    ),
    "StyleMiner.propose": (("context", "POSITIONAL_OR_KEYWORD"),),
    "StyleProfessor.__init__": (("config", "POSITIONAL_OR_KEYWORD"),),
    "StyleProfessor.compile": (("profile", "POSITIONAL_OR_KEYWORD"),),
    "StyleGuideCompiler.compile": (("profile", "POSITIONAL_OR_KEYWORD"),),
    "StyleQualityEvaluator.__init__": (("config", "POSITIONAL_OR_KEYWORD"),),
    "StyleQualityEvaluator.evaluate": (
        ("reference", "POSITIONAL_OR_KEYWORD"),
        ("candidates", "POSITIONAL_OR_KEYWORD"),
    ),
    "StructuredOutputModel.generate": (("request", "POSITIONAL_OR_KEYWORD"),),
    "ConsolidationRunner.__init__": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("config", "POSITIONAL_OR_KEYWORD"),
    ),
    "ConsolidationRunner.plan_once": (
        ("consolidator", "POSITIONAL_OR_KEYWORD"),
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "ConsolidationRunner.execute": (
        ("plan", "POSITIONAL_OR_KEYWORD"),
        ("evaluator", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
    ),
    "ConsolidationRunner.run_once": (
        ("consolidator", "POSITIONAL_OR_KEYWORD"),
        ("scope", "POSITIONAL_OR_KEYWORD"),
        ("checkpoint", "KEYWORD_ONLY"),
        ("evaluator", "KEYWORD_ONLY"),
        ("hooks", "KEYWORD_ONLY"),
        ("run_id", "KEYWORD_ONLY"),
    ),
    "PersonalMemoryQueryEngine.__init__": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("config", "POSITIONAL_OR_KEYWORD"),
        ("semantic_index", "KEYWORD_ONLY"),
        ("relation_index", "KEYWORD_ONLY"),
    ),
    "PersonalMemoryQueryEngine.plan": (
        ("planner", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("now", "KEYWORD_ONLY"),
        ("default_subject", "KEYWORD_ONLY"),
        ("default_subject_id", "KEYWORD_ONLY"),
        ("allowed_subject_ids", "KEYWORD_ONLY"),
    ),
    "PersonalMemoryQueryEngine.execute": (("plan", "POSITIONAL_OR_KEYWORD"),),
    "PersonalMemoryQueryEngine.query": (
        ("planner", "POSITIONAL_OR_KEYWORD"),
        ("query", "POSITIONAL_OR_KEYWORD"),
        ("scopes", "POSITIONAL_OR_KEYWORD"),
        ("now", "KEYWORD_ONLY"),
        ("default_subject", "KEYWORD_ONLY"),
        ("default_subject_id", "KEYWORD_ONLY"),
        ("allowed_subject_ids", "KEYWORD_ONLY"),
    ),
    "audit_store": (
        ("store", "POSITIONAL_OR_KEYWORD"),
        ("config", "KEYWORD_ONLY"),
    ),
    "resolve_content": (
        ("message", "POSITIONAL_OR_KEYWORD"),
        ("resolvers", "POSITIONAL_OR_KEYWORD"),
    ),
}


def test_root_exports_match_versioned_manifest() -> None:
    manifest = json.loads((ROOT / "docs" / "public-api.json").read_text("utf-8"))
    stable = manifest["tiers"]["stable"]
    provisional = manifest["tiers"]["provisional"]
    metadata = manifest["metadata"]
    expected = [*stable, *provisional, *metadata]
    assert manifest["manifest_version"] == 1
    assert manifest["release"] == doppel.__version__
    assert len(expected) == len(set(expected))
    assert set(stable).isdisjoint(provisional)
    assert set(doppel.__all__) == set(expected)
    assert len(doppel.__all__) == len(set(doppel.__all__))
    assert all(hasattr(doppel, name) for name in expected)


def test_wire_model_field_order_is_reviewed_explicitly() -> None:
    actual = {name: tuple(getattr(doppel, name).model_fields) for name in MODEL_FIELDS}
    assert actual == MODEL_FIELDS


def test_extension_protocol_signature_shape_is_reviewed_explicitly() -> None:
    actual = {name: _parameter_shape(_resolve(name)) for name in SIGNATURES}
    assert actual == SIGNATURES


def test_critical_defaults_and_enum_values_are_stable() -> None:
    assert (
        inspect.signature(doppel.DoppelClient.__init__).parameters["backend"].default
        == "sqlite"
    )
    assert (
        inspect.signature(doppel.DoppelClient.process).parameters["processors"].default
        is None
    )
    assert inspect.signature(doppel.MemoryStore.scan).parameters["cursor"].default == ""
    assert inspect.signature(doppel.MemoryStore.scan).parameters["limit"].default == 100
    assert doppel.DeterministicGovernancePolicyConfig().enable_decay is False
    assert (
        inspect.signature(doppel.DoppelClient.restore_personal_memory)
        .parameters["target_state"]
        .default
        is doppel.MemoryState.CANDIDATE
    )
    assert (
        inspect.signature(doppel.ScopedHistoryReader.read).parameters["limit"].default
        == 500
    )
    assert doppel.BatchReadLimits().model_dump() == {
        "max_pages": 100,
        "max_messages": 50_000,
        "max_page_size": 2_000,
    }
    assert doppel.StyleMinerConfig().min_messages == 20
    assert doppel.VectorIndexConfig().model_dump() == {
        "create_extension": False,
        "create_hnsw_index": False,
        "embedding_batch_size": 64,
        "hnsw_m": 16,
        "hnsw_ef_construction": 64,
    }
    assert doppel.StyleMinerConfig().target_scope == "conversation"
    assert doppel.StyleProfessorConfig().include_common_phrases is False
    assert doppel.StyleProfessorConfig().max_prompt_chars == 800
    assert doppel.StyleQualityConfig().min_candidate_messages == 20
    assert doppel.ChatMessage().parts == []
    assert [item.value for item in doppel.MemoryState] == [
        "candidate",
        "confirmed",
        "rejected",
        "superseded",
        "expired",
    ]
    assert [item.value for item in doppel.WriteStatus] == [
        "created",
        "updated",
        "duplicate",
        "skipped",
        "failed",
    ]


def test_custom_store_abstract_surface_does_not_accidentally_expand() -> None:
    assert doppel.MemoryStore.__abstractmethods__ == {
        "capabilities",
        "forget",
        "get",
        "health",
        "is_enabled",
        "list_recent_owner_messages",
        "put",
        "search",
        "transition",
    }


def _resolve(path: str):
    if "." not in path:
        return getattr(doppel, path)
    owner_name, attribute = path.split(".", maxsplit=1)
    return getattr(getattr(doppel, owner_name), attribute)


def _parameter_shape(callable_object) -> tuple[tuple[str, str], ...]:
    return tuple(
        (name, parameter.kind.name)
        for name, parameter in inspect.signature(callable_object).parameters.items()
        if name != "self"
    )
